## 10-1 ndarray 对象创建
（1）从 Python 列表 / 元组创建

In [1]:
import numpy as np
# 从列表创建一维数组
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

# 从嵌套列表创建二维数组
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


（2）使用 NumPy 内置函数创建

In [2]:
import numpy as np
# 创建全零数组
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# 创建全一数组
ones_array = np.ones((2, 4))
print(ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# 创建单位矩阵
eye_array = np.eye(4)
print(eye_array)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# 创建等差数列（不包含stop）
arange_array = np.arange(0, 10, 2)
print(arange_array)

[0 2 4 6 8]


In [6]:
# 创建等间隔数列（包含stop）
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


## 10-2 ndarray 属性与方法

In [7]:
import numpy as np
# 属性示例
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)  # 输出数组形状
print(array.size)   # 输出元素总数
print(array.dtype)  # 输出数据类型
print(array.ndim)   # 输出数组维数

(2, 3)
6
int64
2


In [8]:
array = np.array([[1, 2, 3], [4, 5, 6]])
# 方法示例
# 改变数组形状
reshaped_array = array.reshape((3, 2))
print(reshaped_array)


[[1 2]
 [3 4]
 [5 6]]


In [9]:
# 多维数组展平为一维
flattened_array = array.flatten()
print(flattened_array)

[1 2 3 4 5 6]


In [10]:
# 数组转置
transposed_array = array.transpose()
print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
# 转换数据类型
float_array = array.astype(float)
print(float_array)


[[1. 2. 3.]
 [4. 5. 6.]]


## 10-3 数组索引和切片

In [12]:
import numpy as np
# 基本索引
array = np.array([10, 20, 30, 40, 50])
print(array[0])  # 访问单个元素
array[1] = 25    # 修改单个元素
print(array)

10
[10 25 30 40 50]


In [13]:
# 切片操作
array = np.array([10, 20, 30, 40, 50])
sub_array = array[1:4]
print(sub_array)

[20 30 40]


In [14]:
# 二维数组切片
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array_2d = array_2d[:2, 1:]
print(sub_array_2d)

[[2 3]
 [5 6]]


In [15]:
# 布尔索引
arr = np.array([1, 2, 3, 4, 5])
bool_index = arr > 3  # 生成布尔数组
filtered_arr = arr[bool_index]  # 筛选满足条件的元素
print(bool_index)
print(filtered_arr)

[False False False  True  True]
[4 5]


## 10-4 数组运算
（1）基本数学运算
标量与数组运算

In [16]:
import numpy as np
array = np.array([1, 2, 3, 4])
result_add = array + 10  # 标量加法
result_mul = array * 2    # 标量乘法
print(result_add)
print(result_mul)

[11 12 13 14]
[2 4 6 8]


数组间元素级运算

In [17]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_sum = array1 + array2  # 数组加法
result_prod = array1 * array2  # 数组乘法
print(result_sum)
print(result_prod)

[5 7 9]
[ 4 10 18]


广播机制运算

In [18]:
array = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
result_broadcast1 = array + scalar
print(result_broadcast1)

array1 = np.array([[1, 2, 3], [4, 5, 6]])  # 形状(2,3)
array2 = np.array([10, 20, 30])            # 形状(1,3)
result_broadcast2 = array1 + array2
print(result_broadcast2)

[[11 12 13]
 [14 15 16]]
[[11 22 33]
 [14 25 36]]


（2）统计函数

In [19]:
array = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(array)        # 均值
print(mean_value)

3.0


In [20]:
std_deviation = np.std(array)      # 标准差
print(std_deviation)

1.4142135623730951


In [21]:
variance_value = np.var(array)     # 方差
print(variance_value)

2.0


In [22]:
# 二维数组按轴统计
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
mean_along_axis0 = np.mean(array_2d, axis=0)  # 沿列计算均值
print(mean_along_axis0)

[2.5 3.5 4.5]


In [23]:
std_along_axis1 = np.std(array_2d, axis=1)    # 沿行计算标准差
print(std_along_axis1)

[0.81649658 0.81649658]


In [24]:
max_value = np.max(array)          # 最大值
print(max_value)

5


In [25]:
min_value = np.min(array)          # 最小值
print(min_value)

1


In [26]:
max_along_axis0 = np.max(array_2d, axis=0)    # 沿列计算最大值
min_along_axis1 = np.min(array_2d, axis=1)    # 沿行计算最小值
print(max_along_axis0)
print(min_along_axis1)

[4 5 6]
[1 4]


（3）线性代数运算

In [27]:
import numpy as np
from numpy.linalg import inv, eig

# 矩阵乘法
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
product1 = np.dot(matrix1, matrix2)  # 方法1
product2 = matrix1 @ matrix2         # 方法2（等价）
print(product1)


[[19 22]
 [43 50]]


In [28]:
# 逆矩阵计算
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = inv(matrix)
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
# 特征值与特征向量计算
matrix = np.array([[1, 2], [2, 1]])
eigenvalues, eigenvectors = eig(matrix)
print("特征值:", eigenvalues)
print("特征向量:\n", eigenvectors)

特征值: [ 3. -1.]
特征向量:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## 10-5 逻辑运算与条件筛选
（1）布尔数组

In [30]:
import numpy as np
# 布尔数组生成与逻辑运算
array = np.array([1, 2, 3, 4, 5])
bool_array = array > 3
print(bool_array)

[False False False  True  True]


In [31]:
array1 = np.array([True, False, True])
array2 = np.array([False, False, True])
result_and = np.logical_and(array1, array2)  # 逻辑与
print(result_and)

[False False  True]


In [32]:
result_or = np.logical_or(array1, array2)    # 逻辑或
print(result_or)

[ True False  True]


（2）条件索引与过滤：

In [33]:
# 条件索引与过滤
array = np.array([10, 20, 30, 40, 50])
filtered_array = array[array > 30]  # 筛选大于30的元素
print(filtered_array)

[40 50]


In [34]:
# 条件替换
array = np.array([[1, 2, 3], [4, 5, 6]])
array[array % 2 == 0] = 0  # 偶数替换为0
print(array)


[[1 0 3]
 [0 5 0]]


## 10-6 排序、搜索与计数
（1）数组排序

In [35]:
import numpy as np

array = np.array([3, 1, 2, 5, 4])
sorted_array = np.sort(array)
print(sorted_array)

[1 2 3 4 5]


In [36]:
# 多维数组按轴排序
array_2d = np.array([[10, 1, 8], [9, 5, 6]])
sorted_array_along_axis0 = np.sort(array_2d, axis=0)  # 沿列排序
print(sorted_array_along_axis0)

[[ 9  1  6]
 [10  5  8]]


（2）唯一值与去重

In [37]:
# 唯一值与去重
array = np.array([1, 2, 2, 3, 3, 3, 4])
unique_values = np.unique(array)
print(unique_values)

[1 2 3 4]


## 10-7 Numpy 向量化示例
（1）消除显式循环

In [38]:
import numpy as np
# 消除显式循环
# 循环方式
lst = [1, 2, 3, 4, 5]
result_loop = [x * 2 for x in lst]

# 向量化方式
arr = np.array(lst)
result_vector = arr * 2
print(result_loop)
print(result_vector)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


（2）逐元素操作批量化

In [39]:
# 逐元素操作批量化
# 标量方式
x = 2
result_scalar = x ** 2

# 向量化方式
arr = np.array([1, 2, 3, 4])
result_vector2 = arr ** 2
print(result_scalar)
print(result_vector2)

4
[ 1  4  9 16]


（3）内置数学函数向量化

In [40]:
# 内置数学函数向量化
arr = np.array([0, np.pi / 2, np.pi])
result_sin = np.sin(arr)
print(result_sin)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


（4）简化复杂运算逻辑

In [41]:
# 复杂运算简化
# 循环方式
arr_loop = [1, 2, 3, 4]
result_sum_loop = sum([x**2 for x in arr_loop])

# 向量化方式
arr_vec = np.array([1, 2, 3, 4])
result_sum_vec = np.sum(arr_vec ** 2)
print(result_sum_loop)
print(result_sum_vec)

30
30


## 案例1：线性回归分析

In [42]:
import numpy as np
# （1）导入库并模拟GDP数据
gdp_data = np.array([18.57, 18.71, 18.83, 18.96, 19.08, 19.21, 19.33, 19.45, 19.57, 19.70])

# （2）计算年度增长率
gdp_growth_rate = np.diff(gdp_data) / gdp_data[:-1] * 100
print("GDP 年度增长率:", gdp_growth_rate)

# （3）准备回归模型数据（含偏置项）
X = np.arange(len(gdp_data)).reshape(-1, 1)
y = gdp_data
X_b = np.c_[np.ones((X.shape[0], 1)), X]  # 拼接偏置项

# （4）求解回归系数（文档中省略求解过程，补充标准最小二乘法求解）
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
print("回归系数:", theta_best)

# （5）预测未来GDP
X_new = np.array([[len(gdp_data)], [len(gdp_data) + 1]])  # 未来两年
X_new_b = np.c_[np.ones((X_new.shape[0], 1)), X_new]
gdp_predict = X_new_b.dot(theta_best)
print("未来GDP预测:", gdp_predict)


GDP 年度增长率: [0.75390415 0.64136825 0.69038768 0.63291139 0.68134172 0.62467465
 0.62079669 0.61696658 0.66428206]
回归系数: [18.58109091  0.12442424]
未来GDP预测: [19.82533333 19.94975758]
