# NumPy进阶

参考

+ https://wizardforcel.gitbooks.io/pyda-2e/content/4.html
+ https://wizardforcel.gitbooks.io/pyda-2e/content/a.html
+ https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html
+ https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html


In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
plt.rc('figure', figsize=(10, 6))

In [5]:
np.random.seed(12345)
np.set_printoptions(precision=4, suppress=True)

## 基础部分补充

### 矢量化运算

In [6]:
my_arr = np.arange(1000000)

In [7]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [8]:
my_list = list(range(1000000))

In [9]:
#  for i, x in enumerate(my_list):
#     my_list[i] = x * 2

In [10]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 17 ms
Wall time: 772 ms


In [11]:
my_arr * 2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [12]:
np.multiply(my_arr, 2)

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [13]:
arr1 = np.array([[3.7, -1.2, 2.6], [1, 3, 4]])
arr2 = np.array([[1.2, 0, 1.0], [2,1,0]])

In [14]:
arr1

array([[ 3.7, -1.2,  2.6],
       [ 1. ,  3. ,  4. ]])

In [15]:
arr2

array([[1.2, 0. , 1. ],
       [2. , 1. , 0. ]])

In [16]:
np.maximum(arr1, arr2)

array([[3.7, 0. , 2.6],
       [2. , 3. , 4. ]])

In [17]:
arr1

array([[ 3.7, -1.2,  2.6],
       [ 1. ,  3. ,  4. ]])

In [18]:
np.max(arr1, axis=0)

array([3.7, 3. , 4. ])

In [19]:
arr1 = np.array([[3.7, -1.2, 2.6], [1, 3, 4]])
arr1

array([[ 3.7, -1.2,  2.6],
       [ 1. ,  3. ,  4. ]])

In [20]:
arr1.mean()

2.183333333333333

In [21]:
arr1.mean(axis=0)

array([2.35, 0.9 , 3.3 ])

In [22]:
arr1.argmax(axis=0)

array([0, 1, 1], dtype=int64)

In [23]:
arr1.argsort()

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [26]:
arr1[arr1.argsort()]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [24]:
(arr1 > 0 ) & (arr2 > 0)

array([[ True, False,  True],
       [ True,  True, False]])

In [ ]:
np.logical_and(arr1 > 0 , arr2 > 0)

### 数组的类型转换

In [27]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [28]:
arr.dtype

dtype('float64')

In [29]:
arr.astype('f4')

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1], dtype=float32)

In [30]:
np.maximum(arr, arr)

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [31]:
arr.astype('int32')

array([ 3, -1, -2,  0, 12, 10])

In [32]:
arr.astype('i4')

array([ 3, -1, -2,  0, 12, 10])

In [33]:
arr.astype('?')

array([ True,  True,  True,  True,  True,  True])

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], 
                           dtype=np.string_)

In [35]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [36]:
numeric_strings = np.array(['1.25', '-9.6', '42'], 
                           dtype='S')
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

对于字符型数组，不恰当的指定字符串长度会导致字符被截断。

In [37]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype='S2')

In [38]:
numeric_strings

array([b'1.', b'-9', b'42'], dtype='|S2')

In [39]:
numeric_strings.astype(float)

array([ 1., -9., 42.])

In [40]:
numeric_strings.astype(float).dtype

dtype('float64')

In [41]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([ 858993459, 1072902963,          0, 1072693248,          0,
       1073741824,          0, 1072693248], dtype=uint32)

### 布尔类型数组

In [44]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [45]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [47]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [48]:
bools = np.array([
    [False, False, True, False],
    [True, True, True, True]
])

In [49]:
bools.any()

True

In [50]:
bools.any(axis=1)

array([ True,  True])

In [51]:
bools.all(axis=1)

array([False,  True])

### 基本的索引和切片

In [52]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [56]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [57]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [58]:
arr_slice[:] = 64

In [59]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [60]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [61]:
arr2d[2]

array([7, 8, 9])

In [62]:
arr2d[0][2]

3

In [63]:
arr2d[0, 2]

3

In [64]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d.shape

(2, 2, 3)

In [65]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
old_values = arr3d[0].copy()

In [68]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
# old_values

In [71]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[1, 0]

array([7, 8, 9])

In [73]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [74]:
x[0]

array([7, 8, 9])

In [75]:
arr3d[0].shape

(2, 3)

In [76]:
arr3d[[0]].shape

(1, 2, 3)

### 切片索引

In [77]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [78]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [80]:
arr2d[1, :2]

array([4, 5])

In [81]:
arr2d[:2, 2]

array([3, 6])

In [82]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [83]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 布尔型索引

In [84]:
names = np.array(['Bob', 'Joe', 'Will', 
                  'Bob', 'Will', 'Joe', 'Joe'])

In [85]:
names.shape

(7,)

In [86]:
data = np.random.randn(7, 4)

In [87]:
data

array([[-0.2047,  0.4789, -0.5194, -0.5557],
       [ 1.9658,  1.3934,  0.0929,  0.2817],
       [ 0.769 ,  1.2464,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  1.3529,  0.8864],
       [-2.0016, -0.3718,  1.669 , -0.4386],
       [-0.5397,  0.477 ,  3.2489, -1.0212],
       [-0.5771,  0.1241,  0.3026,  0.5238]])

In [88]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [89]:
data[names == 'Bob']

array([[-0.2047,  0.4789, -0.5194, -0.5557],
       [ 0.275 ,  0.2289,  1.3529,  0.8864]])

In [90]:
data[names == 'Bob', 2:]

array([[-0.5194, -0.5557],
       [ 1.3529,  0.8864]])

In [91]:
data[names == 'Bob', 3]

array([-0.5557,  0.8864])

In [92]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [93]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [94]:
data[~(names == 'Bob')]

array([[ 1.9658,  1.3934,  0.0929,  0.2817],
       [ 0.769 ,  1.2464,  1.0072, -1.2962],
       [-2.0016, -0.3718,  1.669 , -0.4386],
       [-0.5397,  0.477 ,  3.2489, -1.0212],
       [-0.5771,  0.1241,  0.3026,  0.5238]])

In [95]:
cond = names == 'Bob'

In [96]:
data[~cond]

array([[ 1.9658,  1.3934,  0.0929,  0.2817],
       [ 0.769 ,  1.2464,  1.0072, -1.2962],
       [-2.0016, -0.3718,  1.669 , -0.4386],
       [-0.5397,  0.477 ,  3.2489, -1.0212],
       [-0.5771,  0.1241,  0.3026,  0.5238]])

In [97]:
mask = (names == 'Bob') | (names == 'Will')
mask


array([ True, False,  True,  True,  True, False, False])

In [98]:
data[mask]

array([[-0.2047,  0.4789, -0.5194, -0.5557],
       [ 0.769 ,  1.2464,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  1.3529,  0.8864],
       [-2.0016, -0.3718,  1.669 , -0.4386]])

In [99]:
data < 0

array([[ True, False,  True,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [ True, False, False, False]])

In [100]:
data[data<0]

array([-0.2047, -0.5194, -0.5557, -1.2962, -2.0016, -0.3718, -0.4386,
       -0.5397, -1.0212, -0.5771])

In [101]:
data[data < 0] = 0
data

array([[0.    , 0.4789, 0.    , 0.    ],
       [1.9658, 1.3934, 0.0929, 0.2817],
       [0.769 , 1.2464, 1.0072, 0.    ],
       [0.275 , 0.2289, 1.3529, 0.8864],
       [0.    , 0.    , 1.669 , 0.    ],
       [0.    , 0.477 , 3.2489, 0.    ],
       [0.    , 0.1241, 0.3026, 0.5238]])

In [102]:
data[names != 'Joe'] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [1.9658, 1.3934, 0.0929, 0.2817],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.    , 0.477 , 3.2489, 0.    ],
       [0.    , 0.1241, 0.3026, 0.5238]])

## 广播

+ A of shape (3,4,2)
+ B of shape (1,4,2)

In [118]:
# arr1 = np.random.rand(4,3)
# arr2 = np.random.rand(2,1)

In [119]:
# arr1

In [120]:
# arr2

In [121]:
# np.vstack([arr2, arr2])

In [122]:
# arr1 + arr2

In [104]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [105]:
arr = np.random.randn(4, 3)
arr

array([[ 0.0009,  1.3438, -0.7135],
       [-0.8312, -2.3702, -1.8608],
       [-0.8608,  0.5601, -1.2659],
       [ 0.1198, -1.0635,  0.3329]])

In [ ]:
column_mean = arr.mean(axis=0)
column_mean.shape

In [ ]:
column_mean.shape

In [ ]:
demeaned = arr - arr.mean(axis=0)
demeaned

In [ ]:
demeaned.mean(axis=0)

In [ ]:
arr

### 沿其它轴向广播

In [ ]:
row_mean = arr.mean(axis=1)
row_mean.shape

In [ ]:
row_mean.reshape((4, 1))

In [ ]:
demeaned = arr - row_mean.reshape((4, 1))
demeaned

In [ ]:
demeaned.mean(axis=1)

### 通过索引机制插入轴

In [ ]:
arr_1d = np.random.normal(size=3)
arr_1d

In [ ]:
arr_1d[:, np.newaxis].shape

In [ ]:
arr_1d[:, np.newaxis]

In [ ]:
arr_1d[np.newaxis, :].shape

In [ ]:
arr_1d[np.newaxis, :]

In [ ]:
arr_1d.reshape(1,3)

In [ ]:
arr = np.zeros((4, 4))
arr

In [ ]:
(4,1,4)

In [ ]:
arr_3d = arr[:, np.newaxis, :]
arr_3d

In [ ]:
arr_3d.shape

In [ ]:
arr = np.random.randn(3, 4, 5)
arr

In [ ]:
depth_means = arr.mean(axis=2)
depth_means

In [ ]:
depth_means.shape

In [ ]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(axis=2)

### 通过广播设置数组的值

In [ ]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

In [ ]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

In [ ]:
arr[:2] = [[-1.37], [0.509]]
arr

## 花式索引

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
# list(range(10))[[-3, -2]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

In [ ]:
arr[1,0]
arr[5,3]

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
np.array([[0, 0], [1, 1]]).shape

In [ ]:
np.array([[1,2]]).shape

In [ ]:
arr[[[0, 0], [1, 1]], [[1, 2], [1, 2]]]

In [ ]:
arr.__([[0, 0], [1, 1]], [[2,3],[1,2]])

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

### 花式索引的等价函数: take 与 put

In [ ]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

In [ ]:
arr.take(inds)

In [ ]:
arr.put(inds, 42)
arr

In [ ]:
arr.put(inds, [40, 41, 42, 43])
arr

In [ ]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

In [ ]:
arr.take(inds, axis=1)

## 切片函数

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[:3, 2:4]

In [ ]:
# arr[range(3), range(2,4)]

In [ ]:
arr[slice(None,3), slice(2,4)]

In [ ]:
slice(2,a)

In [ ]:
indexer = (slice(None,3), slice(2,4))

In [ ]:
arr[indexer]

In [ ]:
indexer = (slice(None,3), [1,2,3])
arr[indexer]

In [ ]:
arr[slice(None,3), [1,2,3]]

In [ ]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[tuple(indexer)]

In [ ]:
arr_3d = np.random.randn(3, 4, 5)
arr_3d

In [ ]:
arr_3d.mean(axis=0, keepdims=True)[:, 0, 0]

In [ ]:
arr_3d - arr_3d.mean(axis=0, keepdims=True)

In [ ]:
demean_axis(arr_3d, 0)

## 将条件逻辑表述为数组运算

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
arr

In [ ]:
arr > 0

In [ ]:
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
arr = np.random.randn(100)

In [ ]:
(arr > 0).sum() # Number of positive values

## 随机数生成

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

In [ ]:
np.random.seed(1234)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)

## 示例: 随机漫步

In [ ]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [ ]:
walk[:10]

In [ ]:
plt.plot(walk[:100])

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

In [ ]:
plt.plot(walk[:100])

### 一次模拟多个随机漫步

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks

In [ ]:
walks.max()
walks.min()

首次穿越时间，即随机漫步过程中第一次到达某个特定值的时间。

计算达到距离30或-30的最小首次穿越时间

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

In [ ]:
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [ ]:
crossing_times

In [ ]:
crossing_times.mean()

## 求两两距离

来源：https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html

给定两个2D数组A和B，计算A中的每个行向量和B中的每个行向量的欧氏距离。

对于向量$x$和$y$，欧氏距离定义为

\begin{equation}
\sqrt{(x_{0} - y_{0})^2 + (x_{1} - y_{1})^2 + \ldots + (x_{D-1} - y_{D-1})^2} = \sqrt{\sum_{i=0}^{D-1}{(x_{i} - y_{i})^2}}
\end{equation}

In [ ]:
x = np.array([[ 8.54,  1.54,  8.12],
              [ 3.13,  8.76,  5.29],
              [ 7.73,  6.71,  1.31],
              [ 6.44,  9.64,  8.44],
              [ 7.27,  8.42,  5.27]])

In [ ]:
x.shape

In [ ]:
y = np.array([[ 8.65,  0.27,  4.67],
              [ 7.73,  7.26,  1.95],
              [ 1.27,  7.27,  3.59],
              [ 4.05,  5.16,  3.53],
              [ 4.77,  6.48,  8.01],
              [ 7.85,  6.68,  6.13]])

In [ ]:
y.shape

利用公式将计算分解为三步

\begin{equation}
\sum_{i=0}^{D-1}{(x_{i} - y_{i})^2} = \sum_{i=0}^{D-1}{x_{i}^2} + \sum_{i=0}^{D-1}{y_{i}^2} - 2\sum_{i=0}^{D-1}{x_{i} y_{i}}
\end{equation}

1. 对每一对$(x,y)$，求$- 2\sum_{i=0}^{D-1}{x_{i} y_{i}}$
2. 对每一个$x$，求$\sum_{i=0}^{D-1}{x_{i}^2}$
3. 对每一个$y$, 求$\sum_{i=0}^{D-1}{y_{i}^2}$

最后，需要将三项组合到一起

In [ ]:
def pairwise_dists(x, y):
    """ Computing pairwise distances using memory-efficient
    vectorization.

    Parameters
    ----------
    x : numpy.ndarray, shape=(M, D)
    y : numpy.ndarray, shape=(N, D)

    Returns
    -------
    numpy.ndarray, shape=(M, N)
        The Euclidean distance between each pair of
        rows between `x` and `y`."""
    sqr_dists = -2 * np.matmul(x, y.T) # shape [M, N]
    sqr_dists +=  np.sum(x**2, axis=1)[:, np.newaxis] # shape [M, 1]
    # now, `sqr_dists` is of shape [M, N]
    sqr_dists += np.sum(y**2, axis=1) # shape [N,], broadcasted as [1, N]
    # now, `sqr_dists` is of shape [M, N]
    return  np.sqrt(np.clip(sqr_dists, a_min=0, a_max=None))

In [ ]:
pairwise_dists(x, y)